### ISSUE TITLE
Apply CVI components on GUI base layout as Node.js packages

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/sample-implementation-cvi#8]
AS AN Architect
I WANT all GUI developments to be based on versioned e-gov/CVI Node.js packages
SO THAT I could be confident in their quality and them always being up-to-date

#### Source

- [ ] Use #2 as a base

#### Implementing packages

- [ ] Packages information in separate configuration files
- [ ] When changing package version numbers, appropriate changes apply
- [ ] Use `Docker Compose` to run the solution locally

**Comment by turnerrainer** [comment]
Commits missing.

**Comment by ExiRain** [comment]
Updating header/menu package with new changes from Chatbot after TIM updates, with translation and menu opening fixes
https://github.com/buerokratt/sample-implementation-cvi/pull/13
